### ISSUE TITLE
Successfullly compile. Cannot run

### ISSUE THREAD

**Issue by peiyuan-NTU** [mzjb/overlap-only-OpenMX#1]
Error info:

[qchead:67087] *** Process received signal ***
[qchead:67087] Signal: Segmentation fault (11)
[qchead:67087] Signal code: Address not mapped (1)
[qchead:67087] Failing at address: 0x440000e8
[qchead:67087] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f950e3d5630]
[qchead:67087] [ 1] /home/****/installed//lib/libmpi.so.40(MPI_Comm_size+0x37)[0x7f950ea5bd77]
[qchead:67087] [ 2] ./openmx[0x410928]
[qchead:67087] [ 3] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f950de04555]
[qchead:67087] [ 4] ./openmx[0x4107e9]
[qchead:67087] *** End of error message ***
Segmentation fault (core dumped)

The original OpenMX can be installed and run successfully.

**Comment by mzjb** [comment]
I would like to know which compiler did you use.

**Comment by peiyuan-NTU** [comment]
> 
MKLROOT = /home/****/intel/oneapi/mkl/2022.1.0
CC = mpiicc -O3 -xHOST -ip -no-prec-div -qopenmp -I${MKLROOT}/include/fftw -I${HDF5_path}/include -L${HDF5_path}/lib
FC = mpiifort -O3 -xHOST -ip -no-prec-div -qopenmp
LIB= -L$(MKLROOT)/lib/intel64/ -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -mkl=parallel -lifcore -lhdf5

Above is my MAKEFILE
I am using intel compiler

**Comment by mzjb** [comment]
Maybe it is better to check whether your runtime environment is the same as your build environment.
